# Generated by Django 5.1.2 on 2024-10-23 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_kg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('Gas', 'Gas'), ('Electric car', 'Electric car')], max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='steering_wheel',
            field=models.CharField(choices=[('Right', 'Right'), ('Left', 'Left')], max_length=15),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favrites', to=settings.AUTH_USER_MODEL),
        ),
    ]
